# Generated by Django 4.1.2 on 2022-10-25 09:58

import django.core.validators
from django.db import migrations, models
import my_music_app.mymusicapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app.mymusicapp.validators.validate_username_chars]),
        ),
    ]
