# Generated by Django 4.1.2 on 2022-10-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicapp', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
    ]
