# Generated by Django 4.1.2 on 2022-10-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicapp', '0003_profile_age_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Pop', 'Pop Music'), ('Jazz', 'Jazz Music'), ('R&B', 'R&B Music'), ('Rock', 'Rock Music'), ('Country', 'Country Music'), ('Dance Music', 'Dance Music'), ('Hip Hop', 'Hip Hop Music'), ('Other genres', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
            ],
        ),
    ]
