# Generated by Django 4.1.2 on 2022-10-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicapp', '0005_alter_album_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Album Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
